# <span style='font-size:medium'>1.Split this string</span>



In [1]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


**2.Use.format\(\)to print the following string.**

**output should be: The diameter of Earth is 12742kilometers.**


In [4]:
planet="Earth"
diameter=12742
print('The diameter of {} is {} kilometers.' .format(planet, diameter));

The diameter of Earth is 12742 kilometers.


3.In this **nest dictionary grab the word "Hello"**


In [8]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

**Numpy**



In [7]:
import numpy as np

**4.1 Create an array of 10 zeros?**


In [13]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4.2 Create an array of 10 fives?**


In [14]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**5.Create an array of all the even integers from 20 to 35**


In [15]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


In [16]:
x=np.arange(20,35)
y=(x%2==0)
z=x[y]
print(z)

[20 22 24 26 28 30 32 34]


**6.Create a 3x3 matrix with values ranging from 0 to 8**


In [17]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**7.Concatinate a and b**

**a=np.array\(\[1,2,3\]\),b=np.array\(\[4,5,6\]\)**


In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


**Pandas**


**8.Create a dataframe with 3 rows and 2 columns**


In [23]:
import pandas as pd
data={"calories":[220,330,440],"duration":[30,40,50]}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       220        30
1       330        40
2       440        50


**9.Generate the series of dates from 1st Jan ,2023 to 10th Feb,2023**



In [60]:
import pandas as pd
pd.date_range(start='01/01/2023',end='10/02/2023')


DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

**10.Create 2D list to DataFrame** 


In [61]:
import pandas as pd

In [66]:
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['number','tag','number'])
print(df)

   number  tag  number
0       1  aaa      22
1       2  bbb      25
2       3  ccc      24
